### ISSUE TITLE
pdo_sqlsrv 5.12.0 does not compile against PHP 8.5.0

### ISSUE THREAD

**Issue by ZachCallear** [Microsoft/msphpsql#1546]
**PHP version** : 8.5.0

**PHP SQLSRV or PDO_SQLSRV version** : 5.12.0

**Microsoft ODBC Driver version** : 18.5.1.1 (but NA)

**SQL Server version** : NA

**Client operating system** : Arch Linux

**Table schema** : NA

**Problem description**: The pdo_sqlsrv PECL package does not compile with PHP 8.5.0 installed, with compiler error/warning output as follows:
```
In file included from /home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/pdo_dbh.cpp:24:
/home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/php_pdo_sqlsrv_int.h: In function ‘void pdo_reset_dbh_error(pdo_dbh_t*)’:
/home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/php_pdo_sqlsrv_int.h:304:30: error: ‘pdo_dbh_t’ {aka ‘struct _pdo_dbh_t’} has no member named ‘query_stmt_zval’; did you mean ‘query_stmt_obj’?
  304 |         zval_ptr_dtor( &dbh->query_stmt_zval );
      |                              ^~~~~~~~~~~~~~~
      |                              query_stmt_obj
/home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/pdo_dbh.cpp: In function ‘int pdo_sqlsrv_db_handle_factory(pdo_dbh_t*, zval*)’:
/home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/pdo_dbh.cpp:628:41: error: invalid conversion from ‘uint8_t’ {aka ‘unsigned char’} to ‘pdo_error_mode’ [-fpermissive]
  628 |     pdo_error_mode prev_err_mode = dbh->error_mode;
      |                                    ~~~~~^~~~~~~~~~
      |                                         |
      |                                         uint8_t {aka unsigned char}
/home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/pdo_dbh.cpp: In function ‘zend_string* pdo_sqlsrv_dbh_last_id(pdo_dbh_t*, const zend_string*)’:
/home/zach/build/php-pdo_sqlsrv/src/pdo_sqlsrv-5.12.0/pdo_dbh.cpp:1607:41: error: invalid conversion from ‘uint8_t’ {aka ‘unsigned char’} to ‘pdo_error_mode’ [-fpermissive]
 1607 |     pdo_error_mode prev_err_mode = dbh->error_mode;
      |                                    ~~~~~^~~~~~~~~~
      |                                         |
      |                                         uint8_t {aka unsigned char}
make: *** [Makefile:208: pdo_dbh.lo] Error 1
```

**Expected behavior and actual behavior** : The package ought to compile.

**Repro code or steps to reproduce**:

1. Install PHP 8.5.0 .
2. Install PEAR.
3. Run, as root, "pecl install pdo_sqlsrv".

Notes:

My output above is actually from attempting to build the [Arch Linux php-pdo_sqlsrv AUR package](https://aur.archlinux.org/packages/php-pdo_sqlsrv), which I've been using for years.

It builds fine if I downgrade to PHP 8.4.15.

**Comment by David-Engel** [comment]
This is also being discussed in #1539.
