### ISSUE TITLE
PHP 8.5 support

### ISSUE THREAD

**Issue by Matt-PMCT** [Microsoft/msphpsql#1539]
Microsoft should provide timely support for PHP 8.5.

**Comment by lionslair** [comment]
Still no 8.4 version wouldn't hold your breath

**Comment by goozak** [comment]
See [PHP 8.4 support](https://github.com/microsoft/msphpsql/issues/1523)

**Comment by NWASStephenFowles** [comment]
Before I start looking a alternatives for the databases, can we have at least a beta release of a driver that supports 8.5, or at least 8.4. I'm about to have a pen test, and I know I'm going to receive a minor issue at least for out-of-date php releases.

**Comment by CodeMuz** [comment]
+1

**Comment by jansor** [comment]
+1

**Comment by stancl** [comment]
Cannot guarantee this will be usable in production (you probably should wait for a proper release), but if you *just* need this to compile with PHP 8.5, e.g. for CI use, you can use something like this:
```dockerfile
FROM php:8.5.0RC2-cli-bookworm
SHELL ["/bin/bash", "-c"]

RUN apt-get update

RUN apt-get install -y gnupg2 \
    && curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y unixodbc-dev msodbcsql18

RUN mkdir sqlsrv \
    && cd sqlsrv \
    && pecl download pdo_sqlsrv-5.12.0 \
    && tar xzf pdo_sqlsrv-5.12.0.tgz \
    && cd pdo_sqlsrv-5.12.0 \
    && sed -i 's/= dbh->error_mode/= (enum pdo_error_mode) dbh->error_mode/' pdo_dbh.cpp \
    && sed -i 's/zval_ptr_dtor( &dbh->query_stmt_zval );/OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;/' php_pdo_sqlsrv_int.h \
    && phpize \
    && ./configure --with-php-config=$(which php-config) \
    && make -j$(nproc)

# /sqlsrv/pdo_sqlsrv-5.12.0/modules/pdo_sqlsrv.so
```
You can use that in a multi-stage build, just copy over the path in the comment. Note that you will still need the dependencies installed via apt. In a regular build, you could use something like this:
```dockerfile
RUN if [[ "${PHP_VERSION}" == *"8.5"* ]]; then \
        mkdir sqlsrv \
        && cd sqlsrv \
        && pecl download pdo_sqlsrv-5.12.0 \
        && tar xzf pdo_sqlsrv-5.12.0.tgz \
        && cd pdo_sqlsrv-5.12.0 \
        && sed -i 's/= dbh->error_mode/= (enum pdo_error_mode) dbh->error_mode/' pdo_dbh.cpp \
        && sed -i 's/zval_ptr_dtor( &dbh->query_stmt_zval );/OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;/' php_pdo_sqlsrv_int.h \
        && phpize \
        && ./configure --with-php-config=$(which php-config) \
        && make -j$(nproc) \
        && cp modules/pdo_sqlsrv.so $(php -r 'echo ini_get("extension_dir");') \
        && cd / \
        && rm -rf /sqlsrv; \
    else \
        pecl install pdo_sqlsrv; \
    fi

RUN docker-php-ext-enable pdo_sqlsrv
```
If you do not use Docker, the process is basically just:
```sh
# clone repo, or rather download the latest tarball from pecl

# patch pdo_dbh.cpp per https://github.com/php/php-src/pull/17741
sed -i 's/= dbh->error_mode/= (enum pdo_error_mode) dbh->error_mode/' pdo_dbh.cpp

# patch php_pdo_sqlsrv_int.h per https://github.com/php/php-src/pull/17742
sed -i 's/zval_ptr_dtor( &dbh->query_stmt_zval );/OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;/' php_pdo_sqlsrv_int.h

# build as usual
phpize
./configure --with-php-config=$(which php-config)
make -j$(nproc)

# the extension is now in ./modules/
# we can copy it into the php extension_dir like this:
cp modules/pdo_sqlsrv.so $(php -r 'echo ini_get("extension_dir");')
```

I've opened a PR with these changes: https://github.com/microsoft/msphpsql/pull/1543

**Comment by jochem-blok** [comment]
Please add support as soon as possible. We are in the process of upgrading php and would like to use the latest and greatest version. Not another php 8.4 episode please.

**Comment by GTS-MEGHNI** [comment]
Are we getting a support for php 8.5 ?

**Comment by sjayexec** [comment]
+1 for PHP 8.5 support. We are nearing PHP 8.5.0 GA, and there's no sign about whether this will be supported. @stancl 's PR https://github.com/microsoft/msphpsql/pull/1543 and instructions to make it compile works. But hope we get official 8.5 support soon.

**Comment by David-Engel** [comment]
PHP 8.5 support will happen. There is a new team ramping up now. Given the current project state, a GA release is likely in late Jan or Feb.

**Comment by thirdwheel** [comment]
Thank you @stancl for your instructions, my PHP build process now builds the modules for 8.5.

I ran a regression test on 8.4.15 and it does not build with the changes.
```
In file included from /opt/php/8.4.15/include/php/Zend/zend_globals.h:36,
                 from /opt/php/8.4.15/include/php/Zend/zend_compile.h:845,
                 from /opt/php/8.4.15/include/php/Zend/zend_modules.h:24,
                 from /opt/php/8.4.15/include/php/Zend/zend_API.h:25,
                 from /opt/php/8.4.15/include/php/main/php.h:35,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv.h:23,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_init.cpp:21:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h: In function 'void pdo_reset_dbh_error(pdo_dbh_t*)':
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:26: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                          ^~~~~~~~~~~~~~
/opt/php/8.4.15/include/php/Zend/zend_objects_API.h:45:46: note: in definition of macro 'OBJ_RELEASE'
   45 | #define OBJ_RELEASE(obj) zend_object_release(obj)
      |                                              ^~~
In file included from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_init.cpp:24:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:47: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                                               ^~~~~~~~~~~~~~
      |                                               query_stmt
In file included from /opt/php/8.4.15/include/php/Zend/zend_globals.h:36,
                 from /opt/php/8.4.15/include/php/Zend/zend_compile.h:845,
                 from /opt/php/8.4.15/include/php/Zend/zend_modules.h:24,
                 from /opt/php/8.4.15/include/php/Zend/zend_API.h:25,
                 from /opt/php/8.4.15/include/php/main/php.h:35,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv.h:23,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_parser.cpp:23:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h: In function 'void pdo_reset_dbh_error(pdo_dbh_t*)':
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:26: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                          ^~~~~~~~~~~~~~
/opt/php/8.4.15/include/php/Zend/zend_objects_API.h:45:46: note: in definition of macro 'OBJ_RELEASE'
   45 | #define OBJ_RELEASE(obj) zend_object_release(obj)
      |                                              ^~~
In file included from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_parser.cpp:26:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:47: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                                               ^~~~~~~~~~~~~~
      |                                               query_stmt
In file included from /opt/php/8.4.15/include/php/Zend/zend_globals.h:36,
                 from /opt/php/8.4.15/include/php/Zend/zend_compile.h:845,
                 from /opt/php/8.4.15/include/php/Zend/zend_modules.h:24,
                 from /opt/php/8.4.15/include/php/Zend/zend_API.h:25,
                 from /opt/php/8.4.15/include/php/main/php.h:35,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv.h:23,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_stmt.cpp:21:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h: In function 'void pdo_reset_dbh_error(pdo_dbh_t*)':
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:26: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                          ^~~~~~~~~~~~~~
/opt/php/8.4.15/include/php/Zend/zend_objects_API.h:45:46: note: in definition of macro 'OBJ_RELEASE'
   45 | #define OBJ_RELEASE(obj) zend_object_release(obj)
      |                                              ^~~
In file included from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_stmt.cpp:24:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:47: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                                               ^~~~~~~~~~~~~~
      |                                               query_stmt
make: *** [Makefile:217: pdo_init.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:211: pdo_parser.lo] Error 1
In file included from /opt/php/8.4.15/include/php/Zend/zend_globals.h:36,
                 from /opt/php/8.4.15/include/php/Zend/zend_compile.h:845,
                 from /opt/php/8.4.15/include/php/Zend/zend_modules.h:24,
                 from /opt/php/8.4.15/include/php/Zend/zend_API.h:25,
                 from /opt/php/8.4.15/include/php/main/php.h:35,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv.h:23,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_util.cpp:21:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h: In function 'void pdo_reset_dbh_error(pdo_dbh_t*)':
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:26: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                          ^~~~~~~~~~~~~~
/opt/php/8.4.15/include/php/Zend/zend_objects_API.h:45:46: note: in definition of macro 'OBJ_RELEASE'
   45 | #define OBJ_RELEASE(obj) zend_object_release(obj)
      |                                              ^~~
In file included from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_util.cpp:24:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:47: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                                               ^~~~~~~~~~~~~~
      |                                               query_stmt
In file included from /opt/php/8.4.15/include/php/Zend/zend_globals.h:36,
                 from /opt/php/8.4.15/include/php/Zend/zend_compile.h:845,
                 from /opt/php/8.4.15/include/php/Zend/zend_modules.h:24,
                 from /opt/php/8.4.15/include/php/Zend/zend_API.h:25,
                 from /opt/php/8.4.15/include/php/main/php.h:35,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv.h:23,
                 from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_dbh.cpp:21:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h: In function 'void pdo_reset_dbh_error(pdo_dbh_t*)':
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:26: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                          ^~~~~~~~~~~~~~
/opt/php/8.4.15/include/php/Zend/zend_objects_API.h:45:46: note: in definition of macro 'OBJ_RELEASE'
   45 | #define OBJ_RELEASE(obj) zend_object_release(obj)
      |                                              ^~~
In file included from /msphpsql-5.12.0/source/pdo_sqlsrv/pdo_dbh.cpp:24:
/msphpsql-5.12.0/source/pdo_sqlsrv/php_pdo_sqlsrv_int.h:304:47: error: 'pdo_dbh_t' {aka 'struct _pdo_dbh_t'} has no member named 'query_stmt_obj'; did you mean 'query_stmt'?
  304 |         OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;
      |                                               ^~~~~~~~~~~~~~
      |                                               query_stmt
make: *** [Makefile:220: pdo_stmt.lo] Error 1
make: *** [Makefile:214: pdo_util.lo] Error 1
make: *** [Makefile:208: pdo_dbh.lo] Error 1
```

**Comment by stancl** [comment]
That's because those changes are for PHP 8.5, these things were changed between the two versions so the old syntax works with PHP 8.4 and the new syntax works with PHP 8.5. If you take a look at the linked PR it uses version checks to determine which code to use. If you want to test building the PR on 8.5 and 8.4, it'd definitely be appreciated!

**Comment by thirdwheel** [comment]
Ah. I didn't scroll down far enough to see the link to the PR. Thanks!

**Comment by oheil** [comment]
+1

**Comment by SharkMachine** [comment]
> Cannot guarantee this will be usable in production (you probably should wait for a proper release), but if you _just_ need this to compile with PHP 8.5, e.g. for CI use, you can use something like this:
> 
> FROM php:8.5.0RC2-cli-bookworm
> SHELL ["/bin/bash", "-c"]
> 
> RUN apt-get update
> 
> RUN apt-get install -y gnupg2 \
>     && curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
>     && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
>     && apt-get update \
>     && ACCEPT_EULA=Y apt-get install -y unixodbc-dev msodbcsql18
> 
> RUN mkdir sqlsrv \
>     && cd sqlsrv \
>     && pecl download pdo_sqlsrv-5.12.0 \
>     && tar xzf pdo_sqlsrv-5.12.0.tgz \
>     && cd pdo_sqlsrv-5.12.0 \
>     && sed -i 's/= dbh->error_mode/= (enum pdo_error_mode) dbh->error_mode/' pdo_dbh.cpp \
>     && sed -i 's/zval_ptr_dtor( &dbh->query_stmt_zval );/OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;/' php_pdo_sqlsrv_int.h \
>     && phpize \
>     && ./configure --with-php-config=$(which php-config) \
>     && make -j$(nproc)
> 
> # /sqlsrv/pdo_sqlsrv-5.12.0/modules/pdo_sqlsrv.so
> 
> You can use that in a multi-stage build, just copy over the path in the comment. Note that you will still need the dependencies installed via apt. In a regular build, you could use something like this:
> 
> RUN if [[ "${PHP_VERSION}" == *"8.5"* ]]; then \
>         mkdir sqlsrv \
>         && cd sqlsrv \
>         && pecl download pdo_sqlsrv-5.12.0 \
>         && tar xzf pdo_sqlsrv-5.12.0.tgz \
>         && cd pdo_sqlsrv-5.12.0 \
>         && sed -i 's/= dbh->error_mode/= (enum pdo_error_mode) dbh->error_mode/' pdo_dbh.cpp \
>         && sed -i 's/zval_ptr_dtor( &dbh->query_stmt_zval );/OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;/' php_pdo_sqlsrv_int.h \
>         && phpize \
>         && ./configure --with-php-config=$(which php-config) \
>         && make -j$(nproc) \
>         && cp modules/pdo_sqlsrv.so $(php -r 'echo ini_get("extension_dir");') \
>         && cd / \
>         && rm -rf /sqlsrv; \
>     else \
>         pecl install pdo_sqlsrv; \
>     fi
> 
> RUN docker-php-ext-enable pdo_sqlsrv
> 
> If you do not use Docker, the process is basically just:
> 
> # clone repo, or rather download the latest tarball from pecl
> 
> # patch pdo_dbh.cpp per https://github.com/php/php-src/pull/17741
> sed -i 's/= dbh->error_mode/= (enum pdo_error_mode) dbh->error_mode/' pdo_dbh.cpp
> 
> # patch php_pdo_sqlsrv_int.h per https://github.com/php/php-src/pull/17742
> sed -i 's/zval_ptr_dtor( &dbh->query_stmt_zval );/OBJ_RELEASE(dbh->query_stmt_obj);dbh->query_stmt_obj=NULL;/' php_pdo_sqlsrv_int.h
> 
> # build as usual
> phpize
> ./configure --with-php-config=$(which php-config)
> make -j$(nproc)
> 
> # the extension is now in ./modules/
> # we can copy it into the php extension_dir like this:
> cp modules/pdo_sqlsrv.so $(php -r 'echo ini_get("extension_dir");')
> 
> I've opened a PR with these changes: [#1543](https://github.com/microsoft/msphpsql/pull/1543)

It's not production ready, but it works. Thank you.

**Comment by KuenzelIT** [comment]
PHP 8.5 support would be great

**Comment by njames-ac** [comment]
PHP 8.3 is going out of support in 7 days

https://www.php.net/supported-versions.php

**Comment by WanWizard** [comment]
> PHP 8.3 is going out of support in 7 days
> 
> https://www.php.net/supported-versions.php

This ⬆️ !!!

**Comment by jpasher-lazor** [comment]
> > PHP 8.3 is going out of support in 7 days
> > https://www.php.net/supported-versions.php
> 
> This ⬆️ !!!

While it's still desirable to have PHP 8.4+ support, PHP 8.3 only goes out of _active_ support this year. It will still receive security patches for another year, which means any pentest company that dings you for an "out of date" PHP should be fired, because they obviously don't understand how security patches work.

**Comment by WanWizard** [comment]
@jpasher-lazor I know that, it is meant as an indication that Microsoft is running behind. 

I have clients that want me to move to 8.4 or 8.5 for their apps (for whatever reason, the client is king), and I can't because of this issue.

**Comment by hebbet** [comment]
> security patches for another year.

For two years, december 2027.

**Comment by daedalus-codes** [comment]
@stancl Nice work!  

I wonder if taking advantage of [pie](https://github.com/php/pie) for building the PHP extension(s) would be worth looking into.  

I came across this while working through a custom VSCode devcontainer for symfony using [frakenphp](https://github.com/php/frankenphp).

**Comment by njames-ac** [comment]
@daedalus-codes yes it would be great to roll this out with [pie](https://github.com/php/pie)

@hebbet @jpasher-lazor I know there is security support, but I would like to be using the more recent PHP versions, and it is a shame that it is **this project** that is holding my project back but mysql and postgres would be fine on 8.5 .

I understand there is a break in the 8.5 build process ( I experienced that myself last week ) but got it working with PHP 8.3 

My project goes on but it goes on without [pipes](https://www.php.net/releases/8.5/en.php) and [property hooks](https://www.php.net/releases/8.4/en.php)

@David-Engel Looking forward to updates on that timeline 📈

**Comment by remicollet** [comment]
No release for almost 2 years (April 2024). Do you know if this project is still alive?

**Comment by WanWizard** [comment]
> No release for almost 2 years (April 2024). Do you know if this project is still alive?

For Microsofts sake I hope so. We have quite a few clients with their backends in Azure. 
Migrating away from SQL Server is a lot easier and cheaper than migrating away from PHP.

**Comment by SharkMachine** [comment]
Looks like things are happening for official PHP 8.4 support

<img width="598" height="300" alt="Image" src="https://github.com/user-attachments/assets/f82a89cf-e97f-457a-bde1-bf1ebc1881a8" />

**Comment by PiotrZ5** [comment]
How much longer?

**Comment by David-Engel** [comment]
We are revamping the internal test automation. Strictly code-wise, PHP 8.4 and 8.5 support is not large. Tests and test automation infrastructure is requiring a lot of effort to bring it up to compliance standards. We are thinking end of Jan might be doable for a beta and maybe mid-late-Feb for GA. Still some uncertainty about 8.5 since we haven't focused tests on it, yet. But 8.4 is looking good.

**Comment by njames-ac** [comment]
Appreciate the update @David-Engel We are moving some production workloads to use SQL Server and looking to get to PHP 8.5 and then 8.6 as soon as possible.

**Comment by wshmstr** [comment]
PECL: 5.12.0 stable already have **8.5** driver files for the ones who are interested!
https://pecl.php.net/package/pdo_sqlsrv/5.12.0/windows

<img width="832" height="403" alt="Image" src="https://github.com/user-attachments/assets/f8157487-fca5-4b4e-b2f4-8ced48ee846f" />

**Comment by sharppaul** [comment]
@wshmstr Tried it and it seems to be working, not yet in our production but we'll switch a few sites that aren't crucial to the new version/driver soon.

**Comment by delta1186** [comment]
> 8

@David-Engel thanks for the update and I just saw that the 8.4 dropped so that's great news. Sounds like things ramping up. Is a 8.5 beta in the pipeline? 🙏🏻

**Comment by remicollet** [comment]
I noticed 5.13.0beta1 is tagged
https://github.com/microsoft/msphpsql/releases/tag/v5.13.0-beta1

But not published on pecl (nor packagist)

**Comment by hebbet** [comment]
> > 8
> 
> @David-Engel thanks for the update and I just saw that the 8.4 dropped so that's great news. Sounds like things ramping up. Is a 8.5 beta in the pipeline? 🙏🏻 

Soon

https://github.com/microsoft/msphpsql/pull/1565#issuecomment-3812055694

**Comment by David-Engel** [comment]
PECL package for the beta is coming. It should be uploaded today. 8.5 will follow hopefully in a couple weeks. GA will happen by March, at the latest, supporting 8.4, 8.5, and all the latest stuff. Hopefully we will be able to publish to PIE, too.

**Comment by David-Engel** [comment]
5.13 beta1 is up, supporting PHP 8.4:

[PECL :: Package :: pdo_sqlsrv](https://pecl.php.net/package/pdo_sqlsrv)
[PECL :: Package :: sqlsrv](https://pecl.php.net/package/sqlsrv)

Please give it a test and let us know if you experience any issues so that we can address them before the next beta and GA!

**Comment by macintoshplus** [comment]
DLL available for PHP 8.4 and 8.5: https://phpext.phptools.online/extension/pdo_sqlsrv-96

And sqlsrv driver: https://phpext.phptools.online/extension/sqlsrv-95

**Comment by jamesRUS52** [comment]
> DLL available for PHP 8.4 and 8.5: https://phpext.phptools.online/extension/pdo_sqlsrv-96
> 
> And sqlsrv driver: https://phpext.phptools.online/extension/sqlsrv-95

What about . so ?

**Comment by DanielRuf** [comment]
@jamesRUS52 you can find it here under the release:

<img width="573" height="269" alt="Image" src="https://github.com/user-attachments/assets/508fa435-115d-424d-b178-c1fd47e6823e" />

And this is the content:
<img width="698" height="727" alt="Image" src="https://github.com/user-attachments/assets/7e5a82ab-a8cf-4300-883f-f5456aa50c2a" />

Also see the install section at the end of the release: https://github.com/microsoft/msphpsql/releases/tag/v5.13.0-beta1

And take notice of https://github.com/microsoft/msphpsql/issues/1523#issuecomment-3855800186.

**Comment by David-Engel** [comment]
GA is out with PHP 8.4 and 8.5 support! 🚀 

https://github.com/microsoft/msphpsql/releases/tag/v5.13.0
