### ISSUE TITLE
Null characters (0x00) in strings cause premature truncation

### ISSUE THREAD

**Issue by rmc47** [Microsoft/msphpsql#942]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
```
rob@rmc-ssc-web:~/ssc/dist$ dpkg -l | grep mssql
ii  mssql-tools                                                 17.2.0.2-1                                                  amd64        Tools for Microsoft(R) SQL Server(R)
```
 +## SQL Server version
13.0.4224.16 (SQL instance running on Windows; client running on Linux)
 +## Client operating system
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
 +## PHP version
```
PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```
 +## Microsoft ODBC Driver version
```

rob@rmc-ssc-web:~/ssc/dist$ odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/rob/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```
 +## Table schema
 N/A
 +## Problem description
Performing SQL queries with a null (i.e. 0x00) character in the query causes it to be truncated at that point.
 +## Expected behavior and actual behavior
Since null characters can be inserted into nvarchar columns, and can be included in PHP strings, it should be possible to do this.
 +## Repro code or steps to reproduce
 
Failing case, PHP:
```
<?php
$conn = sqlsrv_connect("[server name]", array(
        "UID"=>"sa",
        "PWD"=>"[pwd]",
        "Database"=>"[db]"
    ));
$query = "SELECT 'Hello \0 world';";
echo "Query: $query\n"; // This works as expected, and shows the full query
$stmt = sqlsrv_query($conn, $query);
if( $stmt === false )
{
     echo "Error in executing query.</br>";
     die( print_r( sqlsrv_errors(), true));
}

/* Retrieve and display the results of the query. */
$row = sqlsrv_fetch_array($stmt);
echo "Result: ".$row[0]."\n";
?>
```

Which executes with an error:
```
Error in executing query.</br>Array
(
    [0] => Array
        (
            [0] => 42000
            [SQLSTATE] => 42000
            [1] => 105
            [code] => 105
            [2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'Hello '.
            [message] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'Hello '.
        )

    [1] => Array
        (
            [0] => 42000
            [SQLSTATE] => 42000
            [1] => 102
            [code] => 102
            [2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'Hello '.
            [message] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'Hello '.
        )

)
```

Doing the same thing in C# on a Windows client works as expected, which points me to the PHP driver:
```
using (SqlConnection conn = new SqlConnection("Data Source=.;Integrated Security=true"))
{
    conn.Open();
    using (SqlCommand cmd = conn.CreateCommand())
    {
        cmd.CommandText = "SELECT 'Hello " + (char)0 + " world'";
        using (SqlDataReader reader = cmd.ExecuteReader())
        {
            reader.Read();
            string result = reader.GetString(0);
            Console.WriteLine("Got result: {0}", result); // This correctly returns "Hello \0 world"
        }
    }
}
```

**Comment by yitam** [comment]
@rmc47 please try 
```
$tsql = "SELECT 'Hello \\0 world'";
echo "Query: $tsql\n"; 
$stmt = sqlsrv_query($conn, $tsql);
$row = sqlsrv_fetch_array($stmt);
var_dump($row);
```

The result I got is
```
Query: SELECT 'Hello \0 world';
array(2) {
  [0]=>
  string(14) "Hello \0 world"
  [""]=>
  string(14) "Hello \0 world"
}
```

**Comment by rmc47** [comment]
@yitam thanks for the reply! I think in your example you're returning the characters `\0`, rather than a single character with ASCII value 0, aren't you?

That is, what I'm trying to do is the equivalent of :
`SELECT 'Hello' + Char(0) + ' world';`,
but with the null character actually in the string rather than concatenating it like that.

This works when executed from .NET, but doesn't work in PHP.

**Comment by yitam** [comment]
Thanks @rmc47. I see what you mean.
We will investigate and get back to you.

**Comment by yitam** [comment]
@rmc47 you can achieve the same in PHP with a tweak in the query:

![image](https://user-images.githubusercontent.com/21340756/53598053-99806480-3b58-11e9-891d-78fb7c1582e5.png)

**Comment by rmc47** [comment]
Indeed so - I guess my surprise was that something which was legal in one client library (null bytes within string literals) behaved differently in another, with no mention of it that I could spot in the documentation.

If that's intended behaviour, then I'll work around it.

**Comment by yitam** [comment]
Yes @rmc47 the underlying C/C++ code treats the null character differently, because you might know that it's the terminating character for string literals. You can test your query in Management Studio and you will see what I mean.

**Comment by rmc47** [comment]
Ah, OK, so it's getting turned into a null-terminated string (rather than PHP-like string which is length-defined, in the same way as .NET strings are) further down the stack. Makes sense - thanks.

**Comment by rmc47** [comment]
And now I've found the docs that say the behaviour is undefined: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/character-data-and-c-strings?view=sql-server-2017

> Because character data can be held in a non-null-terminated array and its byte length passed separately, it is possible to embed null characters in character data. However, the behavior of ODBC functions in this case is undefined and it is driver-specific whether a driver handles this correctly. Thus, interoperable applications should always handle character data that can contain embedded null characters as binary data.

Agreed "not a bug" - thanks for your time, @yitam 👍
